<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: roydb.proto

namespace Roydb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>roydb.InsertResponse</code>
 */
class InsertResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 affectedRows = 1;</code>
     */
    private $affectedRows = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $affectedRows
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Roydb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 affectedRows = 1;</code>
     * @return int|string
     */
    public function getAffectedRows()
    {
        return $this->affectedRows;
    }

    /**
     * Generated from protobuf field <code>int64 affectedRows = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAffectedRows($var)
    {
        GPBUtil::checkInt64($var);
        $this->affectedRows = $var;

        return $this;
    }

}

