<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: roydb.proto

namespace Roydb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>roydb.SelectResponse</code>
 */
class SelectResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .roydb.RowData rowData = 1;</code>
     */
    private $rowData;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Roydb\RowData[]|\Google\Protobuf\Internal\RepeatedField $rowData
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Roydb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .roydb.RowData rowData = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRowData()
    {
        return $this->rowData;
    }

    /**
     * Generated from protobuf field <code>repeated .roydb.RowData rowData = 1;</code>
     * @param \Roydb\RowData[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRowData($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Roydb\RowData::class);
        $this->rowData = $arr;

        return $this;
    }

}

