<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: roykv-for-tikv.proto

namespace Roykvtikv;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>roykvtikv.GetAllRequest</code>
 */
class GetAllRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string keyPrefix = 1;</code>
     */
    private $keyPrefix = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $keyPrefix
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\RoykvForTikv::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string keyPrefix = 1;</code>
     * @return string
     */
    public function getKeyPrefix()
    {
        return $this->keyPrefix;
    }

    /**
     * Generated from protobuf field <code>string keyPrefix = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setKeyPrefix($var)
    {
        GPBUtil::checkString($var, True);
        $this->keyPrefix = $var;

        return $this;
    }

}

