<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: roykv-for-tikv.proto

namespace Roykvtikv;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>roykvtikv.ScanRequest</code>
 */
class ScanRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string startKey = 1;</code>
     */
    private $startKey = '';
    /**
     * Generated from protobuf field <code>string startKeyType = 2;</code>
     */
    private $startKeyType = '';
    /**
     * Generated from protobuf field <code>string endKey = 3;</code>
     */
    private $endKey = '';
    /**
     * Generated from protobuf field <code>string endKeyType = 4;</code>
     */
    private $endKeyType = '';
    /**
     * Generated from protobuf field <code>string keyPrefix = 5;</code>
     */
    private $keyPrefix = '';
    /**
     * Generated from protobuf field <code>uint64 limit = 6;</code>
     */
    private $limit = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $startKey
     *     @type string $startKeyType
     *     @type string $endKey
     *     @type string $endKeyType
     *     @type string $keyPrefix
     *     @type int|string $limit
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\RoykvForTikv::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string startKey = 1;</code>
     * @return string
     */
    public function getStartKey()
    {
        return $this->startKey;
    }

    /**
     * Generated from protobuf field <code>string startKey = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setStartKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->startKey = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string startKeyType = 2;</code>
     * @return string
     */
    public function getStartKeyType()
    {
        return $this->startKeyType;
    }

    /**
     * Generated from protobuf field <code>string startKeyType = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setStartKeyType($var)
    {
        GPBUtil::checkString($var, True);
        $this->startKeyType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string endKey = 3;</code>
     * @return string
     */
    public function getEndKey()
    {
        return $this->endKey;
    }

    /**
     * Generated from protobuf field <code>string endKey = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setEndKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->endKey = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string endKeyType = 4;</code>
     * @return string
     */
    public function getEndKeyType()
    {
        return $this->endKeyType;
    }

    /**
     * Generated from protobuf field <code>string endKeyType = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setEndKeyType($var)
    {
        GPBUtil::checkString($var, True);
        $this->endKeyType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string keyPrefix = 5;</code>
     * @return string
     */
    public function getKeyPrefix()
    {
        return $this->keyPrefix;
    }

    /**
     * Generated from protobuf field <code>string keyPrefix = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setKeyPrefix($var)
    {
        GPBUtil::checkString($var, True);
        $this->keyPrefix = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 limit = 6;</code>
     * @return int|string
     */
    public function getLimit()
    {
        return $this->limit;
    }

    /**
     * Generated from protobuf field <code>uint64 limit = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLimit($var)
    {
        GPBUtil::checkUint64($var);
        $this->limit = $var;

        return $this;
    }

}

