<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: roydb.proto

namespace GPBMetadata;

class Roydb
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aca020a0b726f7964622e70726f746f1205726f796462221c0a0d53656c" .
            "65637452657175657374120b0a0373716c18012001280922310a0e53656c" .
            "656374526573706f6e7365121f0a07726f774461746118012003280b320e" .
            "2e726f7964622e526f774461746122260a07526f7744617461121b0a0566" .
            "69656c6418012003280b320c2e726f7964622e4669656c6422710a054669" .
            "656c64120b0a036b657918012001280912110a0976616c75655479706518" .
            "022001280912100a08696e7456616c756518032001280312130a0b646f75" .
            "626c6556616c756518042001280112100a0873747256616c756518052001" .
            "2809120f0a076368617273657418062001280932400a0551756572791237" .
            "0a0653656c65637412142e726f7964622e53656c65637452657175657374" .
            "1a152e726f7964622e53656c656374526573706f6e73652200620670726f" .
            "746f33"
        ), true);

        static::$is_initialized = true;
    }
}

