<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: roydb-udf.proto

namespace GPBMetadata;

class RoydbUdf
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a9b010a0f726f7964622d7564662e70726f746f1208726f796462756466" .
            "22190a0a53696e52657175657374120b0a036e756d180120032801221d0a" .
            "0b53696e526573706f6e7365120e0a06726573756c74180120032801323c" .
            "0a044d61746812340a0353696e12142e726f7964627564662e53696e5265" .
            "71756573741a152e726f7964627564662e53696e526573706f6e73652200" .
            "620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

