<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: roykv.proto

namespace Roykv;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>roykv.AtomicOpRequest</code>
 */
class AtomicOpRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .roykv.AtomicOp atomicOp = 1;</code>
     */
    private $atomicOp;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Roykv\AtomicOp[]|\Google\Protobuf\Internal\RepeatedField $atomicOp
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Roykv::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .roykv.AtomicOp atomicOp = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAtomicOp()
    {
        return $this->atomicOp;
    }

    /**
     * Generated from protobuf field <code>repeated .roykv.AtomicOp atomicOp = 1;</code>
     * @param \Roykv\AtomicOp[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAtomicOp($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Roykv\AtomicOp::class);
        $this->atomicOp = $arr;

        return $this;
    }

}

