<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: roykv.proto

namespace Roykv;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>roykv.BatchAtomicOpReply</code>
 */
class BatchAtomicOpReply extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .roykv.AtomicOpReply atomicOpReply = 1;</code>
     */
    private $atomicOpReply;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Roykv\AtomicOpReply[]|\Google\Protobuf\Internal\RepeatedField $atomicOpReply
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Roykv::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .roykv.AtomicOpReply atomicOpReply = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAtomicOpReply()
    {
        return $this->atomicOpReply;
    }

    /**
     * Generated from protobuf field <code>repeated .roykv.AtomicOpReply atomicOpReply = 1;</code>
     * @param \Roykv\AtomicOpReply[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAtomicOpReply($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Roykv\AtomicOpReply::class);
        $this->atomicOpReply = $arr;

        return $this;
    }

}

