<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: roykv.proto

namespace Roykv;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>roykv.BatchAtomicOpRequest</code>
 */
class BatchAtomicOpRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .roykv.AtomicOpRequest atomicOpRequest = 1;</code>
     */
    private $atomicOpRequest;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Roykv\AtomicOpRequest[]|\Google\Protobuf\Internal\RepeatedField $atomicOpRequest
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Roykv::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .roykv.AtomicOpRequest atomicOpRequest = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAtomicOpRequest()
    {
        return $this->atomicOpRequest;
    }

    /**
     * Generated from protobuf field <code>repeated .roykv.AtomicOpRequest atomicOpRequest = 1;</code>
     * @param \Roykv\AtomicOpRequest[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAtomicOpRequest($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Roykv\AtomicOpRequest::class);
        $this->atomicOpRequest = $arr;

        return $this;
    }

}

