<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: roykv.proto

namespace Roykv;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>roykv.MGetRequest</code>
 */
class MGetRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string keys = 1;</code>
     */
    private $keys;
    /**
     * Generated from protobuf field <code>uint64 txnId = 2;</code>
     */
    private $txnId = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $keys
     *     @type int|string $txnId
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Roykv::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string keys = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getKeys()
    {
        return $this->keys;
    }

    /**
     * Generated from protobuf field <code>repeated string keys = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setKeys($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->keys = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 txnId = 2;</code>
     * @return int|string
     */
    public function getTxnId()
    {
        return $this->txnId;
    }

    /**
     * Generated from protobuf field <code>uint64 txnId = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTxnId($var)
    {
        GPBUtil::checkUint64($var);
        $this->txnId = $var;

        return $this;
    }

}

