<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: roydb-udf.proto

namespace Roydbudf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>roydbudf.SinRequest</code>
 */
class SinRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated double num = 1;</code>
     */
    private $num;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float[]|\Google\Protobuf\Internal\RepeatedField $num
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\RoydbUdf::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated double num = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNum()
    {
        return $this->num;
    }

    /**
     * Generated from protobuf field <code>repeated double num = 1;</code>
     * @param float[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNum($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::DOUBLE);
        $this->num = $arr;

        return $this;
    }

}

